---
# tasks file for DEPLOY-IIS-GENERAL
- name: Creating website folder on IIS
  ansible.windows.win_file:
    path: "{{ WEB_PATH }}"
    state: directory

- name: Create a new application pool in 'Stopped' state
  community.windows.win_iis_webapppool:
    name: "{{ POOL_NAME }}"
    state: stopped

- name: Crate IIS site and stop for update
  community.windows.win_iis_website:
    name: "{{ WEB_NAME }}"
    state: stopped
    port: "{{ WEB_PORT }}"
    ip: "{{ WEB_IP }}"
    hostname: "{{ WEB_HOSTNAME }}"
    application_pool: "{{ POOL_NAME }}"
    physical_path: "{{ WEB_PATH }}"

- name: Copy built-app folder contents recursively to IIS WEB folder
  ansible.windows.win_copy:
    src: "{{ BUILD_ARTIFACT_PATH }}"
    dest: "{{ WEB_PATH }}"

- name: Start application pool
  community.windows.win_iis_webapppool:
    name: "{{ POOL_NAME }}"
    state: started

- name: Start IIS site
  community.windows.win_iis_website:
    name: "{{ WEB_NAME }}"
    state: started
  register: website

- name: IIS Pool Info
  debug:
    var: website


...
